### PR TITLE
FIX: Update topic-list-item to reflect changes in core

### PR DESCRIPTION
**Pull request by oblakeerickson**
This PR in discourse core:

https://github.com/discourse/discourse/pull/8589

makes a breaking change in this plugin. This is a fix for it.

### CODE REVIEW

**Comment by oblakeerickson** [comment]
These tests are likely failing, because the changes in core haven't been applied yet.

**Comment by eviltrout** [comment]
@oblakeerickson if that's the case, does that mean if we merge this it'll break people on the beta/stable branches?

**Comment by oblakeerickson** [comment]
@eviltrout correct. We will need to wait to merge this until the PR in core is merged in.

**Comment by eviltrout** [comment]
@oblakeerickson is there any way we could make it backwards compatible?

**Comment by oblakeerickson** [comment]
I'll give it a shot and let you know.

**Comment by oblakeerickson** [comment]
I was able to add a backwards compatible fix which seems to be working fine locally. Something weird is going on with the qunit tests and they seem to be hanging in a weird spot. I'll keep investigating and see if I can figure out what is actually going on.

**Comment by eviltrout** [comment]
Thanks for the update @oblakeerickson ! sounds good

**Comment by ZogStriP** [comment]
@oblakeerickson should this be merged?

**Pull request merged**
